name: single-workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: docker buildx setup
        uses: docker/setup-buildx-action@v3
      - name: docker login ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker build && docker push
        uses: docker/build-push-action@v5
        with:
          context: inner/dir
          push: true
          tags: ghcr.io/${{ github.repository }}:inner
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max

  run:
    name: Run
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: docker login ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker pull
        run: docker pull ghcr.io/${{ github.repository }}:inner
      - name: docker run
        run: docker run -t ghcr.io/${{ github.repository }}:inner
